In [1]:
import numpy as np
import pandas as pd
import altair as alt
alt.themes.enable('dark')

/var/folders/0t/24t6619s2wjc847jngf_64100000gn/T/ipykernel_35701/2412711460.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


ThemeRegistry.enable('dark')

In [2]:
x = np.array([[1],
              [2],
              [3]])

In [3]:
x.shape

(3, 1)

In [4]:
print(f"A 3-dimensional vector: \n{x}")

A 3-dimensional vector: 
[[1]
 [2]
 [3]]


In [5]:
x = y = np.array([[1],
                  [2],
                  [3]])

In [6]:
x+y

array([[2],
       [4],
       [6]])

In [7]:
np.add(x,y)

array([[2],
       [4],
       [6]])

In [8]:
alpha = 2
x = np.array([[1],
             [2],
             [3]])

In [9]:
alpha * x

array([[2],
       [4],
       [6]])

In [10]:
a, b = 2, 3
x , y = np.array([[2],[3]]), np.array([[4], [5]])

In [11]:
a*x + b*y

array([[16],
       [21]])

In [12]:
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])

In [13]:
x.T @y

array([[-14]])