In [1]:
import numpy as np
import pandas as pd
import altair as alt
alt.themes.enable('dark')

/var/folders/0t/24t6619s2wjc847jngf_64100000gn/T/ipykernel_35701/2412711460.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


ThemeRegistry.enable('dark')

In [2]:
x = np.array([[1],
              [2],
              [3]])

In [3]:
x.shape

(3, 1)

In [4]:
print(f"A 3-dimensional vector: \n{x}")

A 3-dimensional vector: 
[[1]
 [2]
 [3]]


In [5]:
x = y = np.array([[1],
                  [2],
                  [3]])

In [6]:
x+y

array([[2],
       [4],
       [6]])

In [7]:
np.add(x,y)

array([[2],
       [4],
       [6]])

In [8]:
alpha = 2
x = np.array([[1],
             [2],
             [3]])

In [9]:
alpha * x

array([[2],
       [4],
       [6]])

In [10]:
a, b = 2, 3
x , y = np.array([[2],[3]]), np.array([[4], [5]])

In [11]:
a*x + b*y

array([[16],
       [21]])

In [12]:
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])

In [13]:
x.T @y

array([[-14]])

In [14]:
# L2 norm

x = np.array([[3],[4]])

np.linalg.norm(x, 2)

5.0

In [17]:
# L1 norm

x = np.array([[3],[-44]])

np.linalg.norm(x, 1)

47.0

In [18]:
# euclidean distance or L2 norm distance

distance = np.linalg.norm(x-y, 2)
print(f'L_2 distance : {distance}')

L_2 distance : 41.012193308819754


In [19]:
# calculate the cosine

x, y = np.array([[1], [2]]), np.array([[5], [7]])

# here we translate the cos(theta) definition
cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.988]]


In [20]:
cos_inverse = np.arccos(cos_theta)
print(f'angle in radiants = {np.round(cos_inverse, 3)}')

angle in radiants = [[0.157]]


In [21]:
# get degrees

degrees = cos_inverse * ((180)/np.pi)
print(f'angle in degrees = {np.round(degrees, 3)}')

angle in degrees = [[8.973]]


In [22]:
x = np.array([[2], [0]])
y = np.array([[0], [2]])

cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.]]


In [23]:
cos_inverse = np.arccos(cos_theta)
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in radiants = {np.round(cos_inverse, 3)}\nangle in degrees ={np.round(degrees, 3)} ')

angle in radiants = [[1.571]]
angle in degrees =[[90.]] 
